const transactions = [
  {
    id: 1,
    transactionDate: "2022-01-01",
    invoiceNumber: "123",
    payer: "John",
    payee: "Jane",
    amount: "100",
    usdEquivalent: "100",
    status: "paid",
  },
  {
    id: 2,
    transactionDate: "2022-01-01",
    invoiceNumber: "123",
    payer: "John",
    payee: "Jane",
    amount: "100",
    usdEquivalent: "100",
    status: "paid",
  },
  {
    id: 3,
    transactionDate: "2022-01-01",
    invoiceNumber: "123",
    payer: "John",
    payee: "Jane",
    amount: "100",
    usdEquivalent: "100",
    status: "paid",
  },
  {
    id: 4,
    transactionDate: "2022-01-01",
    invoiceNumber: "123",
    payer: "John",
    payee: "Jane",
    amount: "100",
    usdEquivalent: "100",
    status: "paid",
  },
  {
    id: 5,
    transactionDate: "2022-01-01",
    invoiceNumber: "123",
    payer: "John",
    payee: "Jane",
    amount: "100",
    usdEquivalent: "100",
    status: "paid",
  },
  {
    id: 6,
    transactionDate: "2022-01-01",
    invoiceNumber: "123",
    payer: "John",
    payee: "Jane",
    amount: "100",
    usdEquivalent: "100",
    status: "paid",
  },
  {
    id: 7,
    transactionDate: "2022-01-01",
    invoiceNumber: "123",
    payer: "John",
    payee: "Jane",
    amount: "100",
    usdEquivalent: "100",
    status: "paid",
  },
];

export default transactions;
